[ { _id: 573357c489ed8fcc3dd00321,
    updatedBy: 56b8f6b88092490beb8501f4,
    updatedAt: Thu May 12 2016 14:00:10 GMT-0400 (EDT),
    createdBy: 56b8f6b88092490beb8501f4,
    createdAt: Wed May 11 2016 12:03:16 GMT-0400 (EDT),
    slug: 'carrier-service',
    title: 'Carrier Service',
    __v: 1,
    attribute_one: 'Industry Attribute One',
    attribute_three: '',
    attribute_two: '',
    content: 'When it comes to network connections, customers need options. That’s why we provide our clients with a wide variety of solutions to address their unique needs. Whether it’s Ethernet Access, IP Transport, Wavelength, TDM Service, or Wireless Backhaul, we have the right solution to help every customer optimize network productivity.',
    description: 'this is the description',
    heading: 'Dedicated to delivering the network of the future and providing exceptional service.',
    svg_icon: 'partners_carriers',
    lastEditAt: Wed May 11 2016 13:20:36 GMT-0400 (EDT),
    editor: 56b8f6b88092490beb8501f4,
    checkoutTime: Thu May 12 2016 14:00:10 GMT-0400 (EDT),
    resource_four:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_three:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_two:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_one:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    media_buffet:
     { media_section_two:
        { title: '<p>rightmedia<strong>title</strong></p>',
          type: 'None',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: {} },
       facts:
        { title: '<p>factoid<strong>title</strong></p>',
          featured_image: {} },
       values: { content: '', title: '<p>values<strong>title</strong></p>' },
       media_section_one:
        { title: '<p>leftmedia<strong>title</strong></p>',
          type: 'None',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: {} } },
    custom_ordered_services:
     [ 54c137b1c76198496cef691f,
       54c141b6c76198496cef6928,
       54c140cbc76198496cef6926 ],
    state: 'published' },
  { _id: 54c13e19c76198496cef6920,
    updatedBy: 56b8f6b88092490beb8501f4,
    updatedAt: Thu May 12 2016 12:11:04 GMT-0400 (EDT),
    createdBy: 54c0601528d69d3655bc48fb,
    createdAt: Thu Jan 22 2015 13:14:49 GMT-0500 (EST),
    slug: 'hospitality',
    title: 'Hospitality',
    content: 'Your hotel guests want to feel like they are at home. We don\'t provide a single solution to the Hospitality sector, rather Cox Business partners with hotels to understand your specific needs and provide a solution that is customized to what you need and what will satisfy your guests. That\'s what makes us unique.',
    heading: 'Provide a superior experience that strengthens brand loyalty.',
    __v: 3,
    icon:
     { filename: '4b6912b7671d9188aee9e818beffa1bb.png',
       path: 'public/uploads/images',
       size: 18621,
       filetype: 'image/png' },
    svg_icon: 'industry_hospitality',
    attribute_one: 'Hotels',
    attribute_three: 'Bed & Breakfasts',
    attribute_two: 'Restaurants',
    description: 'Provide a superior experience that strengthens brand loyalty.',
    lastEditAt: Wed May 11 2016 13:10:31 GMT-0400 (EDT),
    checkoutTime: null,
    resource_four:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_three:
     { description: 'High-quality, reliable entertainment and information are critical to delivering a quality guest experience.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/cb_hospitality_suite.pdf',
       title: 'Cox Hospitality Suite',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_two:
     { description: 'Provide an experience your guests will always appreciate.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-industries-hospitality-suite.pdf',
       title: 'Hospitality Suite datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_one:
     { description: 'Provide an experience that helps your guests stay connected.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/DS-CBHWF_Cox_Business_Hospitality_Wifi.pdf',
       title: 'Hospitality WiFi',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    media_buffet:
     { story:
        { title: '<p>Success<strong>Story</strong></p>',
          featured_image: [Object],
          content: [Object] },
       video:
        { background: [Object],
          title: '<p>Cox<strong>Hospitality</strong></p>',
          video: [Object],
          video_choice: true },
       media_section_two:
        { title: '<p>Success<strong>Story</strong></p>',
          type: 'Story',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] },
       facts:
        { content: '<p><strong>10/10</strong></p>\r\n<p>Developers love Nick\'s code.</p>',
          title: '<p>Cox<strong>Facts</strong></p>',
          featured_image: [Object] },
       values:
        { content: '<p>It\'s easy to do business with us because we focus on one thing:&nbsp;<em><strong>what your business needs.</strong></em></p>',
          title: '<p>Cox<strong>Values</strong></p>' },
       media_section_one:
        { title: '<p>Cox<strong>Hospitality</strong></p>',
          type: 'Video',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] } },
    custom_ordered_services:
     [ 54c137b1c76198496cef691f,
       54c140cbc76198496cef6926,
       54c141b6c76198496cef6928 ],
    state: 'published' },
  { _id: 54c13ecec76198496cef6921,
    updatedBy: 5547b1479dab8f7556ad00c6,
    updatedAt: Wed Feb 17 2016 14:42:08 GMT-0500 (EST),
    createdBy: 54c0601528d69d3655bc48fb,
    createdAt: Thu Jan 22 2015 13:17:50 GMT-0500 (EST),
    slug: 'education',
    title: 'Education',
    content: 'Educational institutions today are faced with tons of data that have the capability to transform education. For institutions looking to take advantage of "big data", Cox offers innovative networking technology that will maximize the potential of big data by providing secure, real-time connectivity. Choosing us means, a reliable, secure backbone, supported by our people located right in your area, making us an ideal partner to help add more flexibility into your learning models.',
    heading: 'Cox Business delivers innovation to schools and universities.',
    __v: 7,
    icon:
     { filename: 'e03db50666db8f4ba48e09f8198b28dd.png',
       path: 'public/uploads/images',
       size: 18621,
       filetype: 'image/png' },
    svg_icon: 'industry_education',
    attribute_one: 'Schools',
    attribute_three: '',
    attribute_two: 'Universities',
    description: 'Cox Business delivers innovation to schools and universities.',
    lastEditAt: Mon Oct 26 2015 13:30:38 GMT-0400 (EDT),
    checkoutTime: null,
    resource_four:
     { description: 'Growth in older and part-time students is dictating the need for more flexible and accessible options for students. ',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/cb_higher_ed_article.pdf',
       svg_icon: 'resources_whitepaper',
       title: 'Higher Education Connectivity and Voice Solutions',
       resource_type: false },
    resource_three:
     { description: 'Connectivity, a Foundation for Educational Excellence. ',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/metro-ethernet-brochure-education.pdf?campcode=resources_data_1003',
       title: 'Metro Ethernet for Education datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_two:
     { description: 'Premium Internet for complex business data needs, powered by the Cox Business Fiber-Optic Network. ',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-optical-internet.pdf?campcode=resources_data_101110',
       title: 'Optical Internet datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_one:
     { description: 'Finally, students can experience TV anywhere on campus.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/CB_Campus_Connect_v2.pdf',
       title: 'Campus Connect datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    media_buffet:
     { story:
        { title: '<p>Success<strong>Story</strong></p>',
          featured_image: [Object],
          content: [Object] },
       video:
        { background: [Object],
          title: '<p>Cox<strong>Education</strong></p>',
          video: [Object],
          video_choice: true },
       media_section_two:
        { title: '<p>Success<strong>Story</strong></p>',
          type: 'Story',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] },
       facts:
        { content: '<p><strong>10/10</strong></p>\r\n<p>Developers love Nick\'s code.</p>',
          title: '<p>Cox<strong>Facts</strong></p>',
          featured_image: [Object] },
       values:
        { content: '<p>Partnering with local institutions is our pleasure, after all, our kids go to school there too.</p>',
          title: '<p>Cox<strong>Values</strong></p>' },
       media_section_one:
        { title: '<p>Cox<strong>Education</strong></p>',
          type: 'Video',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] } },
    custom_ordered_services:
     [ 54c141b6c76198496cef6928,
       54c14170c76198496cef6927,
       54c137b1c76198496cef691f ],
    state: 'published' },
  { _id: 54c13ee0c76198496cef6922,
    updatedBy: 56b8f6b88092490beb8501f4,
    updatedAt: Sun May 08 2016 14:16:47 GMT-0400 (EDT),
    createdBy: 54c0601528d69d3655bc48fb,
    createdAt: Thu Jan 22 2015 13:18:08 GMT-0500 (EST),
    slug: 'healthcare',
    title: 'Healthcare',
    content: 'Responding to your patients\' needs quickly, reliably and securely can enhance their level of medical care. Our communications services can provide better ways to manage your patients\' data, improve efficiency and minimize costs.\r\n',
    heading: 'Our healthcare solutions serve hospitals and medical offices nationwide.',
    __v: 5,
    icon:
     { filename: '6fca50ffdf07f3a69eed889bacdcc7aa.png',
       path: 'public/uploads/images',
       size: 18621,
       filetype: 'image/png' },
    svg_icon: 'industry_healthcare',
    attribute_one: 'Hospitals',
    attribute_three: '',
    attribute_two: 'Medical Offices',
    description: 'Our healthcare solutions serve hospitals and medical offices nationwide.',
    lastEditAt: Fri Feb 19 2016 15:21:53 GMT-0500 (EST),
    checkoutTime: null,
    resource_four:
     { description: 'Orthopedic practice of nearly 50 years with four locations in Ohio: Westlake, Lakewood, Lorain, and Avon.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/case_study_healthcare_ortho_assoc_OH.pdf',
       title: 'Testimonial - Orthopedic Associates in Ohio',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_three:
     { description: 'Hospitals recognize that IT plays a critical role in enabling better overall patient care, so investments in technology are increasingly seen as a key strategic decision.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/overview_healthcare_delivery_solutions.pdf',
       title: 'Healthcare Delivery Solutions',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_two:
     { description: 'For enterprises and small practices alike, cable’s a rising star on the healthcare IT scene.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/CTAM_biz_smartbrief_special_report_2015_03_18.pdf',
       title: 'CTAM e-Health Revolution',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_one:
     { description: 'A scalable option that enables you to provide your patients, visitors and guests with a homelike viewing experience.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/cb_bulk_HD_healthcare.pdf',
       title: 'Bulk HD Select for Healthcare',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    media_buffet:
     { story:
        { title: '<p>Success<strong>Story</strong></p>',
          featured_image: [Object],
          content: [Object] },
       video:
        { background: [Object],
          title: '<p>Cox<strong>Healthcare</strong></p>',
          video: [Object],
          video_choice: true },
       media_section_two:
        { title: '<p>Success<strong>Story</strong></p>',
          type: 'Story',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] },
       facts:
        { content: '<p><strong>10/10</strong></p>\r\n<p>Developers love Nick\'s code.</p>',
          title: '<p>Cox<strong>Facts</strong></p>',
          featured_image: [Object] },
       values:
        { content: '<p>As a healthcare provider, your business demands, and deserves, the best in communications solutions.</p>',
          title: '<p>Cox<strong>Values</strong></p>' },
       media_section_one:
        { title: '<p>Cox<strong>Healthcare</strong></p>',
          type: 'Video',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] } },
    custom_ordered_services:
     [ 54c14170c76198496cef6927,
       54c141b6c76198496cef6928,
       54c137b1c76198496cef691f ],
    state: 'published' },
  { _id: 54c13ef2c76198496cef6923,
    updatedBy: 552fc022ad357d7b755e89dc,
    updatedAt: Wed Feb 17 2016 14:42:08 GMT-0500 (EST),
    createdBy: 54c0601528d69d3655bc48fb,
    createdAt: Thu Jan 22 2015 13:18:26 GMT-0500 (EST),
    slug: 'government',
    title: 'Government',
    content: 'We understand federal, state and local governments work with a fixed budget and work hard to deliver customized solutions within that budget. And as your needs grows, Cox Business grows with you. We offer a complete portfolio of telecommunications solutions to meet the diverse needs of municipal, state, and federal agencies. Our innovative solutions provide true network diversity, continuity of operations, and the security government organizations require. Whether you have a single communications need or want to rebuild your entire network, Cox can help you strengthen your government enterprise with cutting-edge solutions that are delivered on time and on budget',
    heading: 'Cox Business understands government — and how crucial continuity of operations and security are to your mission.',
    __v: 4,
    icon:
     { filename: 'd347b6db0119fca457ab8950e959571c.png',
       path: 'public/uploads/images',
       size: 18621,
       filetype: 'image/png' },
    svg_icon: 'industry_government',
    attribute_one: 'Federal',
    attribute_three: 'Local Governments',
    attribute_two: 'State',
    description: 'Cox Business understands government — and how crucial continuity of operations and security are to your mission.',
    checkoutTime: null,
    resource_four:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_three:
     { description: 'Advanced phone features in a hosted, affordable phone system.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-voicemanager-ip-centrex.pdf',
       title: 'VoiceManager IP Centrex datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_two:
     { description: 'Robust protection against online, network and virus threats.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-business-securitysuite.pdf',
       title: 'Security Suite',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_one:
     { description: 'How the “Internet of Things” will affect IT... and why resistance is futile.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/internet-of-things-spiceworks-cox-report.pdf',
       title: 'The Devices are Coming! datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    media_buffet:
     { story:
        { title: '<p>Success<strong>Story</strong></p>',
          featured_image: [Object],
          content: [Object] },
       video:
        { background: [Object],
          title: '<p>Cox<strong>Government</strong></p>',
          video: [Object],
          video_choice: true },
       media_section_two:
        { title: '<p>Success<strong>story</strong></p>',
          type: 'Story',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] },
       facts:
        { content: '<p><strong>10/10</strong></p>\r\n<p>Developers love Nick\'s code.</p>',
          title: '<p>Cox<strong>Facts</strong></p>',
          featured_image: [Object] },
       values:
        { content: '<p><span class="s1">You can count on us to help you maintain cost, efficiency, and reliability.</span></p>',
          title: '<p>Cox<strong>Values</strong></p>' },
       media_section_one:
        { title: '<p>Cox<strong>Government</strong></p>',
          type: 'Video',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] } },
    custom_ordered_services:
     [ 54c137b1c76198496cef691f,
       54c140cbc76198496cef6926,
       54c14170c76198496cef6927 ],
    state: 'published' },
  { _id: 54c13f0dc76198496cef6924,
    updatedBy: 552fc022ad357d7b755e89dc,
    updatedAt: Wed May 11 2016 13:06:11 GMT-0400 (EDT),
    createdBy: 54c0601528d69d3655bc48fb,
    createdAt: Thu Jan 22 2015 13:18:53 GMT-0500 (EST),
    slug: 'general-business',
    title: 'General Business',
    content: 'As a Cox Digital Community, your residents will enjoy the next generation of entertainment and communication services. From On DEMAND and HD programming to high-speed internet and low-cost phone service, our scalable network helps ensure your community is exactly where residents want to live.',
    heading: 'Know your residents have the reliable solutions they need.',
    __v: 4,
    icon:
     { filename: '1882912a7648c3ea946737b4d034b6ce.png',
       path: 'public/uploads/images',
       size: 18621,
       filetype: 'image/png' },
    svg_icon: 'industry_residentialcommunities',
    attribute_one: 'Residential Communities',
    attribute_three: '',
    attribute_two: '',
    description: 'Know your residents have the reliable solutions they need.',
    lastEditAt: Tue Apr 21 2015 10:15:46 GMT-0400 (EDT),
    checkoutTime: Wed May 11 2016 13:06:09 GMT-0400 (EDT),
    resource_four:
     { description: 'High-speed, highly-reliable communications platform.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-private-line.pdf?campcode=xl_data_8_0908',
       title: 'Private Line datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_three:
     { description: 'Advanced phone features in a hosted, affordable phone system. ',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-voicemanager-ip-centrex.pdf',
       title: 'VoiceManager IP Centrix datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_two:
     { description: 'Up-to-the-minute information and entertainment.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-video-basic.pdf?campcode=pm_btv_btv-resources_btv-datasheet_pdf_071511_lnk-1',
       title: 'Business TV datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_one:
     { description: 'Reliable, secure, high-speed business internet. ',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/DS-CBI_Cox_Business_Internet_Data_Sheet_06172014.pdf?campcode=xl_data_05012014',
       title: 'Business Internet datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    media_buffet:
     { story:
        { title: '<p>Success<strong>Story</strong></p>',
          featured_image: [Object],
          content: [Object] },
       video:
        { background: [Object],
          title: '<p>Cox<strong>Business</strong></p>',
          video: [Object],
          video_choice: true },
       media_section_two:
        { title: '<p>Success<strong>Story</strong></p>',
          type: 'Story',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] },
       facts:
        { content: '<p><strong>10/10</strong></p>\r\n<p>Developers love Nick\'s code.</p>',
          title: '<p>Cox<strong>Facts</strong></p>',
          featured_image: [Object] },
       values:
        { content: '<p><span class="s1">We are your partners in business diversity, service continuity, and reliable security.</span></p>',
          title: '<p>Cox<strong>Values</strong></p>' },
       media_section_one:
        { title: '<p>Cox<strong>Business</strong></p>',
          type: 'Video',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] } },
    custom_ordered_services:
     [ 54c137b1c76198496cef691f,
       54c141b6c76198496cef6928,
       54c140cbc76198496cef6926 ],
    state: 'published' },
  { _id: 54c13f1fc76198496cef6925,
    updatedBy: 552fc022ad357d7b755e89dc,
    updatedAt: Wed Feb 17 2016 14:42:08 GMT-0500 (EST),
    createdBy: 54c0601528d69d3655bc48fb,
    createdAt: Thu Jan 22 2015 13:19:11 GMT-0500 (EST),
    slug: 'real-estate',
    title: 'Real Estate',
    content: 'Cox Business provides tenants with a single source for reliable connection to phone, high-speed internet, television capabilities, and more via the Cox high-speed fiber optic-based network. We offer scalable solutions to ensure our solutions are an exact fit for your properties. Partnering with Cox Business ensures you offer the services that commercial business tenants want and need.',
    heading: 'Look to our solutions to strengthen your bottom line.',
    __v: 1,
    icon:
     { filename: 'b883b7e55c00cdf3be922ca1d8973532.png',
       path: 'public/uploads/images',
       size: 18621,
       filetype: 'image/png' },
    svg_icon: 'industry_realestate',
    attribute_one: 'Leased',
    attribute_three: 'Properties',
    attribute_two: 'Development',
    description: ' Cox Business provides tenants with a single source for reliable connection to phone, high-speed internet, television capabilities, and more.',
    checkoutTime: null,
    resource_four:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_three:
     { description: '',
       resource_link: '',
       title: '',
       svg_icon: 'favorites_star',
       resource_type: false },
    resource_two:
     { description: 'Complete office backup.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/ds-data-onlinebackup.pdf',
       title: 'Online Backup datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    resource_one:
     { description: 'Reliable. Scalable. Effective business voice telecommunications services.',
       resource_link: 'http://www.cox.com/wcm/en/business/datasheet/pri-digital-trunk.pdf',
       title: 'PRI Trunk Service datasheet',
       svg_icon: 'resources_whitepaper',
       resource_type: false },
    media_buffet:
     { story:
        { title: '<p>Success<strong>Story</strong></p>',
          featured_image: [Object],
          content: [Object] },
       video: { background: [Object], title: '' },
       media_section_two:
        { title: '<p>success<strong>story</strong></p>',
          type: 'Story',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] },
       facts:
        { content: '<p><strong>10/10</strong></p>\r\n<p>Developers love Nick\'s code.</p>',
          title: '<p>Cox<strong>Facts</strong></p>',
          featured_image: [Object] },
       values:
        { content: '<p>Rely on our expertise to know your tenants are connected and covered.</p>',
          title: '<p>Cox<strong>Values</strong></p>' },
       media_section_one:
        { title: '<p> <strong></strong></p>',
          type: 'None',
          story: [Object],
          image: {},
          video: [Object],
          thumbnail: [Object] } },
    custom_ordered_services:
     [ 54c141b6c76198496cef6928,
       54c140cbc76198496cef6926,
       54c137b1c76198496cef691f ],
    state: 'published' } ]
